### ISSUE TITLE
Create Users Collection

### ISSUE THREAD

**Issue by nathancy** [adventure-portal/adventure-portal#7]
Implement collection to store data of individual users

Key features:
- Able to display user's interests
- Show pinned activities
- About me

**Comment by dylannakahodo** [comment]
See [Bowfolios Profile Collection](https://github.com/bowfolios/bowfolios/blob/master/app/imports/api/profile/ProfileCollection.js) for ideas

**Comment by dylannakahodo** [comment]
Fields:
* Name (First/Last)
* Email
* Picture
* Interests
* About me/Bio
* Current Activities
